# 端口
server:
  port: 9023

# spring配置
spring:
  # 数据源
  datasource:
    username: root
    password: xxxxx
    url: jdbc:mysql://120.26.85.88:3306/layui_study
  # thymeleaf缓存
  thymeleaf:
    cache: false
  # 应用名称
  application:
    name: LayuiProject

